### ISSUE TITLE
The msm results are different between VariableBaseMSM::multi_scalar_mul with multi_scalar_mult_arkworks when generated scalars’ lengths are not divisible by 32

### ISSUE THREAD

**Issue by miachel-cf** [supranational/sppark#1]
@dot-asm 

I noticed the sppark code on accelerating msm on GPU, it's great. but I met a problem in that the case msm_correctness failed after changing the generated points length.

the command is :  `cargo test --features=bls12_377`

the resuts is:
![image](https://user-images.githubusercontent.com/86712787/190946354-ae16194a-85da-4a5e-bfc1-9f967d4facc9.png)

the code is:
```
fn msm_correctness() {
    let test_npow = std::env::var("TEST_NPOW").unwrap_or("15".to_string());
    let npoints_npow = i32::from_str(&test_npow).unwrap();

    let (points, scalars) =
        **//util::generate_points_scalars::<G1Affine>(1usize << npoints_npow);
        util::generate_points_scalars::<G1Affine>(237);**

    let msm_result = multi_scalar_mult_arkworks(points.as_slice(), unsafe {
        std::mem::transmute::<&[_], &[BigInteger256]>(scalars.as_slice())
    })
    .into_affine();

    let arkworks_result =
        VariableBaseMSM::multi_scalar_mul(points.as_slice(), unsafe {
            std::mem::transmute::<&[_], &[BigInteger256]>(scalars.as_slice())
        })
        .into_affine();

    assert_eq!(msm_result, arkworks_result);
}
```

**Comment by miachel-cf** [comment]
1. thanks, already updated the issue's title for this problem.
2. Yes, this input is just for testing the correctness. I want to test performance with out actual application under GPU finally. Do you know the reason now and then plan to fix it?

**Comment by dot-asm** [comment]
1. thanks for the report
2. It's kind of a trick question. You'll measure improvement over CPU for amount on inputs smaller than ~2^20, but there is room for improvement for smaller amount of inputs. In other words, whatever you measure today, it will better in no-so-distant future, and the improvement coefficient will be better for smaller amount of inputs.

**Comment by dot-asm** [comment]
> You'll measure improvement over CPU for amount of inputs smaller than ~2^20

This came out wrong. It's not like you won't measure improvement for the amount of inputs larger than 2^20. Quite the contrary. What I'm trying to say is that the improvement coefficient for a smaller amount is won't be as good as for the larger. [And the it will improve.]
