### ISSUE TITLE
sppark/ff/mont_t.cuh(721): error: identifier "i" is undefined

### ISSUE THREAD

**Issue by eleven-pixel** [supranational/sppark#13]
+ c++ -DSECTOR_SIZE_512MiB -g -O2 -Ideps/spdk-v22.09/include -Ideps/spdk-v22.09/isa-l/.. -Ideps/spdk-v22.09/dpdk/build/include -D__ADX__ -fno-omit-frame-pointer -Wall -Wextra -Wno-unused-parameter -Wno-missing-field-initializers -fno-strict-aliasing -march=native -Wformat -Wformat-security -D_GNU_SOURCE -fPIC -fstack-protector -fno-common -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=2 -DSPDK_GIT_COMMIT=4be6d3043 -pthread -Ideps/spdk-v22.09/include -Ideps/spdk-v22.09/isa-l/.. -Ideps/spdk-v22.09/dpdk/build/include -Ideps/sppark -Ideps/sppark/util -Ideps/blst/src -c sealing/supra_seal.cpp -o obj/supra_seal.o -Wno-subobject-linkage
deps/sppark/ff/mont_t.cuh(721): error: identifier "i" is undefined
          even[i] = even[i+1] = 0;
               ^

deps/sppark/ff/mont_t.cuh(729): error: expected a ">"
              for (i = 0; i < n; i += 2) {
                               ^

deps/sppark/ff/mont_t.cuh(735): error: expression must be a modifiable lvalue
                      : "+r"(odd[n+i-1]), "+r"(carry));
                             ^

deps/sppark/ff/mont_t.cuh(735): error: an asm operand must have scalar type
                      : "+r"(odd[n+i-1]), "+r"(carry));
                        ^

deps/sppark/ff/mont_t.cuh(742): error: expression must be a modifiable lvalue
                      : "+r"(even[n+i+1]), "+r"(carry));
                             ^

deps/sppark/ff/mont_t.cuh(742): error: an asm operand must have scalar type
                      : "+r"(even[n+i+1]), "+r"(carry));
                        ^

6 errors detected in the compilation of "pc2/cuda/pc2.cu".
deps/sppark/ff/mont_t.cuh(721): error: identifier "i" is undefined
          even[i] = even[i+1] = 0;
               ^

deps/sppark/ff/mont_t.cuh(729): error: expected a ">"
              for (i = 0; i < n; i += 2) {
                               ^

deps/sppark/ff/mont_t.cuh(735): error: expression must be a modifiable lvalue
                      : "+r"(odd[n+i-1]), "+r"(carry));
                             ^

deps/sppark/ff/mont_t.cuh(735): error: an asm operand must have scalar type
                      : "+r"(odd[n+i-1]), "+r"(carry));
                        ^

deps/sppark/ff/mont_t.cuh(742): error: expression must be a modifiable lvalue
                      : "+r"(even[n+i+1]), "+r"(carry));
                             ^

deps/sppark/ff/mont_t.cuh(742): error: an asm operand must have scalar type
                      : "+r"(even[n+i+1]), "+r"(carry));
                        ^

6 errors detected in the compilation of "pc2/cuda/pc2.cu".
deps/sppark/ff/mont_t.cuh(721): error: identifier "i" is undefined
          even[i] = even[i+1] = 0;
               ^

deps/sppark/ff/mont_t.cuh(729): error: expected a ">"
              for (i = 0; i < n; i += 2) {
                               ^

deps/sppark/ff/mont_t.cuh(735): error: expression must be a modifiable lvalue
                      : "+r"(odd[n+i-1]), "+r"(carry));
                             ^

deps/sppark/ff/mont_t.cuh(735): error: an asm operand must have scalar type
                      : "+r"(odd[n+i-1]), "+r"(carry));
                        ^

deps/sppark/ff/mont_t.cuh(742): error: expression must be a modifiable lvalue
                      : "+r"(even[n+i+1]), "+r"(carry));
                             ^

deps/sppark/ff/mont_t.cuh(742): error: an asm operand must have scalar type
                      : "+r"(even[n+i+1]), "+r"(carry));
                        ^

6 errors detected in the compilation of "pc2/cuda/pc2.cu".
deps/sppark/ff/mont_t.cuh(721): error: identifier "i" is undefined
          even[i] = even[i+1] = 0;
               ^

deps/sppark/ff/mont_t.cuh(729): error: expected a ">"
              for (i = 0; i < n; i += 2) {
                               ^

deps/sppark/ff/mont_t.cuh(735): error: expression must be a modifiable lvalue
                      : "+r"(odd[n+i-1]), "+r"(carry));
                             ^

deps/sppark/ff/mont_t.cuh(735): error: an asm operand must have scalar type
                      : "+r"(odd[n+i-1]), "+r"(carry));
                        ^

deps/sppark/ff/mont_t.cuh(742): error: expression must be a modifiable lvalue
                      : "+r"(even[n+i+1]), "+r"(carry));
                             ^

deps/sppark/ff/mont_t.cuh(742): error: an asm operand must have scalar type
                      : "+r"(even[n+i+1]), "+r"(carry));
                        ^

6 errors detected in the compilation of "pc2/cuda/pc2.cu".
+ ar rvs obj/libsupraseal.a obj/pc1.o obj/pc2.o obj/pc2_link.o obj/ring_t.o obj/streaming_node_reader_nvme.o obj/supra_seal.o obj/sector_parameters.o obj/sha_ext_mbx2.o
ar: creating obj/libsupraseal.a
a - obj/pc1.o
ar: obj/pc2.o: No such file or directory

**Comment by eleven-pixel** [comment]
static inline mont_t dot_product(const mont_t a[], const mont_t* b,
                                     size_t len, size_t stride_b = 1)
    {
        mont_t tmp;
        wide_t even;
        uint32_t odd[2*n-2], carry;

        for (size_t i = 0; i < 2*n-2; i++)
            even[i] = odd[i] = 0;
        even[i] = even[i+1] = 0;


Is there a missing brace here?

**Comment by dot-asm** [comment]
Oops! Got carried away yesterday. Fixed. Thanks!

**Comment by dot-asm** [comment]
> missing brace here?

No, single-expression loop body doesn't require braces.
