### ISSUE TITLE
scalar is not constant

### ISSUE THREAD

**Issue by qy3u** [supranational/sppark#2]
Hi! 
I have noticed that `scalars` argument in the pippenger funciton has a type of `const scalar_t*`
https://github.com/supranational/sppark/blob/d9670078e40684c43903b2d8b0645f11d0f00b05/msm/pippenger.cuh#L44-L45

but  the elements of `scalars` will be convert to `scalar_T` and write back inplace in the pippenger function.
https://github.com/supranational/sppark/blob/d9670078e40684c43903b2d8b0645f11d0f00b05/msm/pippenger.cuh#L158-L176

After the pippenger function executed, scalars are not the same as before. The type definition of `scalars` may be a little misleading.

**Comment by dot-asm** [comment]
I'll fix this at next occasion. Thanks!
