### ISSUE TITLE
how to understand the implementation of `reduce(uint32_t temp[4])`

### ISSUE THREAD

**Issue by cliff0412** [supranational/sppark#25]
the rust code below is quite easy to understand. i.e reduce x_hi_hi, then x_hi_lo. 
```rust
fn reduce128(x: u128) -> GoldilocksField {
    let (x_lo, x_hi) = split(x); // This is a no-op
    let x_hi_hi = x_hi >> 32;
    let x_hi_lo = x_hi & EPSILON;

    let (mut t0, borrow) = x_lo.overflowing_sub(x_hi_hi);
    if borrow {
        branch_hint(); // A borrow is exceedingly rare. It is faster to branch.
        t0 -= EPSILON; // Cannot underflow.
    }
    let t1 = x_hi_lo * EPSILON;
    let t2 = unsafe { add_no_canonicalize_trashing_input(t0, t1) };
    GoldilocksField(t2)
}
```

however the below cuda inline assembly code of 128 reduction is not easy to understand; possible to provide some docs? thanks
```cpp
1    inline void reduce(uint32_t temp[4])
 2   {
3        uint32_t carry;
4 # if __CUDA_ARCH__ >= 700
5        asm("sub.cc.u32 %0, %0, %3; subc.cc.u32 %1, %1, %4; subc.u32 %2, 0, 0;"
6            : "+r"(temp[0]), "+r"(temp[1]), "=r"(carry)
7            : "r"(temp[2]), "r"(temp[3]));
8        asm("add.cc.u32 %0, %0, %2; addc.u32 %1, %1, %3;"
9            : "+r"(temp[1]), "+r"(carry)
10            : "r"(temp[2]), "r"(temp[3]));
11
 12       asm("mad.lo.cc.u32 %0, %3, %4, %0; madc.hi.cc.u32 %1, %3, %4, %1; addc.u32 %2, 0, 0;"
  13          : "+r"(temp[0]), "+r"(temp[1]), "=r"(temp[2])
 14           : "r"(carry), "r"(gl64_device::W));
 15       asm("mad.lo.cc.u32 %0, %2, %3, %0; madc.hi.u32 %1, %2, %3, %1;"
 16           : "+r"(temp[0]), "+r"(temp[1])
 17           : "r"(temp[2]), "r"(gl64_device::W));
18  # else
19        uint32_t b0, b1;
 20       asm("add.cc.u32 %0, %2, %3; addc.u32 %1, 0, 0;"
 21           : "=r"(b0), "=r"(b1)
 22           : "r"(temp[2]), "r"(temp[3]));
  23      asm("sub.cc.u32 %0, %0, %3; subc.cc.u32 %1, %1, %4; subc.u32 %2, 0, 0;"
24            : "+r"(temp[0]), "+r"(temp[1]), "=r"(carry)
25            : "r"(b0), "r"(b1));
26        asm("add.cc.u32 %0, %0, %2; addc.u32 %1, %1, %3;"
27            : "+r"(temp[0]), "+r"(temp[1])
 28           : "r"(-carry), "r"(carry));
 29       asm("add.cc.u32 %0, %0, %1; addc.u32 %1, 0, 0;"
30            : "+r"(temp[1]), "+r"(temp[2]));

31 #  if __CUDA_ARCH__ >= 700
 32       asm("mad.lo.cc.u32 %0, %2, %3, %0; madc.hi.u32 %1, %2, %3, %1;"
 33           : "+r"(temp[0]), "+r"(temp[1])
  34          : "r"(temp[2]), "r"(gl64_device::W));
35 #  else
 36       asm("add.cc.u32 %0, %0, %2; addc.u32 %1, %1, 0;"
 37           : "+r"(temp[0]), "+r"(temp[1])
 38           : "r"(-temp[2]));
39 #  endif
40 # endif
41        asm("mov.b64 %0, {%1, %2};" : "=l"(val) : "r"(temp[0]), "r"(temp[1]));
 42   }
```

**Comment by cliff0412** [comment]
i think i can understand it now. please correct me if i am wrong
let `E = 1<<32`
let `n = n0 + n1 * E + n2 *E^{2} + n3 * E^{3}`, then
`n = n0 + n2 * E^2 + E*(n1+n3*E^2)`.
since `E^2 = E - 1` (Goldilocks field's property in reduction)
`n = n0 + n2 * (E-1) + E*(n1+n3*(E-1))`.
`n = n0 - n2 +n2*E+ E*(n1-n3 + n3*E)`.
`n = n0 -n2 + E(n1-n3 +n2) + n3*E^2`.
line 5 computes `n0 - n2` and set to temp[0]; & computes `n1-n3` and sets to temp[1]
line 8 computes `n1- n3 + n2`; add n3 with carry and put it to carry.

let `c` be the carry, at position of E^2, it is actually c * E^2. it could be further reduced to  c * (E- 1) = c * W
line 12 is to reduce the carry part to temp[0], temp[1], and temp[2].
if temp[2] still exist. line 15 will reduce it to temp[0], temp[1] similar as above.
at this step. only temp[0] and temp[1] will contains value and return as the result.


the question:
<span style="red">why line 32 and line 15 is duplicated</span>? reduction by two times to ensure that there is no remanning at temp[2]?

**Comment by dot-asm** [comment]
The fact that the issue was not closed was not an invitation for further discussions, but providing you with an opportunity to acknowledge the state of affairs, as **regrettable** as it is.
