### ISSUE TITLE
gl64, the + result is incorrect when both operands > p

### ISSUE THREAD

**Issue by cliff0412** [supranational/sppark#27]
for example, if GL64_PARTIALLY_REDUCED not defined.
```
let mut a: u64 = 0xffffffff_f0000fff;
let mut b: u64 = 0xffffffff_f0000fff;
```
the expected output should be 0x1e0001ffc. however, the actual result is 0xffffffffe0001ffe, after reduction,  it is 0xe0001ffd, result is not matched

**Comment by dot-asm** [comment]
If you pass a random pointer to memcpy, would you blame libc for failing your application? Same here, if you don't define GL64_PARTIALLY_REDUCED, you're expected to uphold your side of the "contract" and pass exclusively fully reduced inputs.
