### ISSUE TITLE
what is the definition of `const uint32_t& M0` in mont_t.cuh

### ISSUE THREAD

**Issue by cliff0412** [supranational/sppark#34]
any documentation on how to understand the M0 in the Montgomery Reduction? Or which Montgomery Reduction algorithm is implemented? As of my shallow understanding of normal Mongt Implementation. There is no M0 involved. Maybe you are using another trick or algorithm implementation here?

**Comment by dot-asm** [comment]
This is a textbook question, and as already pointed out earlier, we don't have resources to answer such questions. Granted, the name choice is not directly reflective of the Wikipedia page, but the core idea is textbook, so it shouldn't be hard to figure out it's the variable customarily referred to as `modulus'`.
