### ISSUE TITLE
failed to run custom build command for `sppark v0.1.5'

### ISSUE THREAD

**Issue by dltom2024** [supranational/sppark#35]
error occurred: Command "nvcc" "-ccbin=C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\VC\\Tools\\MSVC\\14.29.30133\\bin\\HostX64\\x64\\cl.exe" "-Xcompiler" "-nologo" "-Xcompiler" "-MD" "-G" "-Xcompiler" "-Z7" "-Xcompiler" "-Brepro" "-I" "D:\\hash\\aleo\\sppark-0.1.5" "-Xcompiler" "-W4" "-o" "D:\\hash\\aleo\\sppark-0.1.5\\rust\\target\\debug\\build\\sppark-9d1ea8dff2ab2e4d\\out\\src/lib.o" "-c" "src/lib.cpp" with args "nvcc" did not execute successfully (status code exit code: 2).
windows10 ,nvcc=12.3，gcc = 13.2, rustc = 1.75.0  gpu= rtx4060,

**Comment by dot-asm** [comment]
Formally speaking the description is incomplete to act upon. It's not generally sufficient to say "nvcc did not execute successfully," you have to provide error messages... However! In **this** particular case it's actually known fact that sppark doesn't work on Windows, so even if error messages were provided, the answer would still be the same, "yeah, it doesn't work." While Windows is not actually supported, the tip of the repository can be compiled on Windows. So if you want to help, test that and report back, an additional data point would be appreciated. Though it's important to set the expectations right. For example, you mention gcc, but nvcc doesn't support gcc on Windows, only Visual C... So what's up with you mentioning gcc? Well, it's a question for you to ask yourself...

On related note, it's actually known that CUDA and sppark work under WSL, Windows Subsystem for Linux, version 2, so consider even this as alternative.
