### ISSUE TITLE
a new complile error in gpu_t.cuh file when the cuda is 11.8

### ISSUE THREAD

**Issue by jimmyopenBTS** [supranational/sppark#43]
The following warnings were emitted during compilation:

warning: In file included from /root/.cargo/registry/src/rsproxy.cn-8f6827c7555bfaf8/sppark-0.1.6/sppark/util/gpu_t.cuh:13,
warning:                  from src/lib.cpp:2:
warning: /root/.cargo/registry/src/rsproxy.cn-8f6827c7555bfaf8/sppark-0.1.6/sppark/util/gpu_t.cuh: In member function ‘void event_t::wait(cudaStream_t)’:
warning: /root/.cargo/registry/src/rsproxy.cn-8f6827c7555bfaf8/sppark-0.1.6/sppark/util/gpu_t.cuh:45:50: error: too few arguments to function ‘cudaError_t cudaStreamWaitEvent(cudaStream_t, cudaEvent_t, unsigned int)’
warning:      {   CUDA_OK(cudaStreamWaitEvent(stream, event));   }
warning:                                                   ^
warning: /root/.cargo/registry/src/rsproxy.cn-8f6827c7555bfaf8/sppark-0.1.6/sppark/util/exception.cuh:13:24: note: in definition of macro ‘CUDA_OK’
warning:      cudaError_t code = expr;                                \
warning:                         ^~~~
warning: In file included from /usr/include/channel_descriptor.h:61,
warning:                  from /usr/include/cuda_runtime.h:95,
warning:                  from src/lib.cpp:1:
warning: /usr/include/cuda_runtime_api.h:2240:58: note: declared here
warning:  extern __host__ __cudart_builtin__ cudaError_t CUDARTAPI cudaStreamWaitEvent(cudaStream_t stream, cudaEvent_t event, unsigned int flags);
warning:                                                           ^~~~~~~~~~~~~~~~~~~
warning: In file included from /root/.cargo/registry/src/rsproxy.cn-8f6827c7555bfaf8/sppark-0.1.6/sppark/util/gpu_t.cuh:13,
warning:                  from src/lib.cpp:2:
warning: /root/.cargo/registry/src/rsproxy.cn-8f6827c7555bfaf8/sppark-0.1.6/sppark/util/gpu_t.cuh: In member function ‘void* stream_t::Dmalloc(size_t) const’:
warning: /root/.cargo/registry/src/rsproxy.cn-8f6827c7555bfaf8/sppark-0.1.6/sppark/util/gpu_t.cuh:72:17: error: ‘cudaMallocAsync’ was not declared in this scope
warning:          CUDA_OK(cudaMallocAsync(&d_ptr, sz, stream));
warning:                  ^~~~~~~~~~~~~~~
warning: /root/.cargo/registry/src/rsproxy.cn-8f6827c7555bfaf8/sppark-0.1.6/sppark/util/exception.cuh:13:24: note: in definition of macro ‘CUDA_OK’
warning:      cudaError_t code = expr;                                \
warning:                         ^~~~
warning: /root/.cargo/registry/src/rsproxy.cn-8f6827c7555bfaf8/sppark-0.1.6/sppark/util/gpu_t.cuh:72:17: note: suggested alternative: ‘cudaMallocArray’
warning:          CUDA_OK(cudaMallocAsync(&d_ptr, sz, stream));
warning:                  ^~~~~~~~~~~~~~~
warning: /root/.cargo/registry/src/rsproxy.cn-8f6827c7555bfaf8/sppark-0.1.6/sppark/util/exception.cuh:13:24: note: in definition of macro ‘CUDA_OK’
warning:      cudaError_t code = expr;                                \
warning:                         ^~~~
warning: /root/.cargo/registry/src/rsproxy.cn-8f6827c7555bfaf8/sppark-0.1.6/sppark/util/gpu_t.cuh: In member function ‘void stream_t::Dfree(void*) const’:
warning: /root/.cargo/registry/src/rsproxy.cn-8f6827c7555bfaf8/sppark-0.1.6/sppark/util/gpu_t.cuh:76:17: error: ‘cudaFreeAsync’ was not declared in this scope
warning:      {   CUDA_OK(cudaFreeAsync(d_ptr, stream));   }

**Comment by dot-asm** [comment]
Here is the problem. The error log lists cudaFreeAsync that was added in 11.x. It complains about the 3rd argument to cudaStreamWaitEvent while 11.x assigned a default value to it. In other words the presented error log does not align with the assertion that it's a problem with 11.8. Note that 11.8 is exercised in github actions. Granted, it's only a test compilation, but  I've just verified that I can in fact  **execute** PoCs compiled with 11.8. In other words everything points toward problem with **your** CUDA installation and not sppark.
