### ISSUE TITLE
question about kernel optimization

### ISSUE THREAD

**Issue by jinz2014** [supranational/sppark#51]
Hello,
Is there some reference or explanation about the optimization techniques in the "bit_rev_permutation_z" kernel ? The kernel is a highly optimized version of "bit_rev_permutation".

**Comment by dot-asm** [comment]
Unfortunately this is not an educational project and we don't have resources to go into that much detail, not upon a random request on github. I can only say that the goal is to maximize so called coalesced loads/stores from/to global memory, when adjacent threads address adjacent memory addresses, and "abuse" the shared memory with bit reversal addressing instead.
