### ISSUE TITLE
Rust binding planned?

### ISSUE THREAD

**Issue by vmx** [supranational/sppark#6]
This is more of a question than an issue, but I ask it here to prevent double efforts.

Are there plans to create a Rust binding for sppark, similar to the binding blst has? Or is the plan that Rust users would always create their own custom crate similar to the PoCs or `pasta-msm`?

**Comment by dot-asm** [comment]
The original plan was to use Rust infrastructure just as a vessel to distribute the C++ templates [and some helper code]. In other words, so far the answer was "the latter." But it's not written in stone. As we gather the experience integrating it into real-life applications and discover practical usage patterns, it might change...
