### ISSUE TITLE
Documentation of CUDA MSM limitations

### ISSUE THREAD

**Issue by vmx** [supranational/sppark#7]
When I call `mult_pippenger()` from Rust with <= 512 bases I get a segfault: `signal: 11, SIGSEGV: invalid memory reference`. It would be cool if such limitations would be documented.

**Comment by shenrn1998** [comment]
Greetings!

I met the same problem as you mentioned. Our team tried it for several times to locate the specific problem.

Here's what we found: for function "**invoke**" at msm/pippenger.cuh, there is slightly difference between variable "N" and "this->N". When they are not equal (our tests shows that this->N equals 5, and N could be 1,2,3,4,5 when points.len()<=512), the result of GPU will differ from that of CPU.

To solve the problem, you may adjust function "**collect**" at msm/pippenger.cuh to something like this:
![image](https://github.com/supranational/sppark/assets/50269749/5e2e6e82-b058-4e19-8685-f735e4b75106)

And also, you should pay attention to function "**invoke**" who calls "**collect**" at msm/pippenger.cuh.

Hope this could help you.

**Comment by dot-asm** [comment]
There was a major MSM makeover and it's no longer a problem. Well, at least for example `env TEST_NPOW=7 cargo test --release --features=bls12_381` works if you pull from github.
