### ISSUE TITLE
NTT curve support 

### ISSUE THREAD

**Issue by dong-ai-7** [supranational/sppark#9]
// Maximum domain size supported. Can be adjusted at will, but with the
// target field in mind. Most fields handle up to 2^32 elements, BLS12-377
// can handle up to 2^47, alt_bn128 - 2^28...

I noted that there are some comments about NTT implementation in curve alt_bn128, but it's currently undone. Is there anything special (parameter) to cope with compared with BLS_377 and BLS_381? Will this part of implementation be published soon?

**Comment by Iridescent-gcrace** [comment]
Can I ask when you will support BN254 curve? Will this part of implementation be published soon?

**Comment by dot-asm** [comment]
Fixed in 90f90ed6c352a002779f5428e4ad4593950fc2c7. Thanks.
